# build workflow
name: build
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'FirstTimeInstaller/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'FirstTimeInstaller/**'
      - '**.md'
  workflow_dispatch:
jobs:
  # Pester test job
  pester-test:
    runs-on: windows-2019
    steps:
      # checkout
      - uses: actions/checkout@v2
      # Runs Pester all *.tests.ps1 scripts
      - name: Run Pester tests
        env:
          GH_API_ACCESS_TOKEN: ${{ secrets.GH_API_ACCESS_TOKEN }}
        run: |
          # Pester is not installed by default on Windows Server 2019 - PowerShell 7
          Install-Module Pester -Force
          Import-Module Pester
          Write-Output "Run Pester $(Get-InstalledModule Pester | Select-Object -ExpandProperty Version) ..."
          $config = [PesterConfiguration]@{
              Run = @{
                  Path = './PSCoreUpdate.Tests/'
                  # TestExtension is default setting (.Tests.ps1)
              }
              Output = @{
                  Verbosity = 'Detailed'
              }
          }
          Invoke-Pester -Configuration $config
        shell: pwsh
